### ISSUE TITLE
Slow updates while watch app in background

### ISSUE THREAD

**Issue by Aleksandraa20** [loic2665/HeartRateToWeb#3]
Tizen 5.5.0.1 Galaxy watch 3 lte
Constant hr monitor on
1000ms updates

As long as the screen stays on and the app is displayed it updates as expected
Once screen shuts off, goes to the “always on” screen, or app is run in the background 
updates drop off to once every 2-3 seconds after ~ 5 seconds
up to ~3 minutes after screen off updates are about once every 14 seconds
at ~4 minutes once every 20 seconds

**Comment by loic2665** [comment]
Hi, 

Thanks for your feedback, I know this issue, but for now i'm still thinking for a solution.

This occurs because as a webapp, i can't have a lot of option of powermanagement.
I need to make a native webapp in C/C++ language to have a workaround of these limitation.

On the samsung galaxy watch I set the delay to 500ms to get an update every second while in background/ "always on" mode.

This is power management restriction from samsung.

Loïc

**Comment by greysquidcat** [comment]
I built this app, but Samsung gives a warning about power usage.

**Comment by F9Alejandro** [comment]
You can always try using the microphone permission, since bixby has a wake word and is always listening, might be a good work around until something better is found.

**Comment by fti7** [comment]
Any Updates on this? It would be a great app if it doesnt slow down/stop after the App is in the Background :-)

**Comment by loic2665** [comment]
Ok again, I'm just dumb, using the wrong feature, now the screen is NOT going to sleep and goes to a minimal brightness while sending the heartrate. 

I'm pushing an update to the samsung app asap, code is already here.
