### ISSUE TITLE
ip resets each launch

### ISSUE THREAD

**Issue by ragekillen** [loic2665/HeartRateToWeb#5]
can you add a config file to fix this?

**Comment by mrdeadlocked** [comment]
same here

**Comment by loic2665** [comment]
Hi,

It's currently in the todo list, I plan to rewrite the app, to get a native app instead of a webapp,
and to have the ability to save the last user ip/port/delay. 

I currently have no ETA because I have a lot of work for school.. student life.. ^^

Thanks for your interest!

Loïc

**Comment by greysquidcat** [comment]
I made an app that uses the app shared preferences feature.
Luckily I am on school break right now.
It really depends if you can use API 3.0 or not unfortunately.

**Comment by carlos-garcia** [comment]
setting tizen api level to 4.0 is working for me.. made that PR
https://github.com/loic2665/HeartRateToWeb/pull/9

**Comment by loic2665** [comment]
I'm doing a fix for this, sadly, i forgot my computer charger at work and I have currently 10% battery, I will finish this at work Monday (or Sunday if i'm motivated to move here) 

Concerning the #9 I've merged it.

**Comment by mrdeadlocked** [comment]
Great news! it will be nice to have the fixes with a new release

**Comment by F9Alejandro** [comment]
When making the app make sure it is BasicUI and to use new tizen app instead of tizen app.

Note: When dealing with number entry or anything that deals with the keypad in the app, make sure to hit the back button to get out of the typing entry, but not to get confused with the home key as it will not do what you expect (unless you are going back to the home screen).
